import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { repoRoot } from "./story-model.mjs";

test("narration verification contract stays fail-closed", () => {
  const contract = JSON.parse(readFileSync(join(repoRoot, "content/evidence/narration/contract-v1.json"), "utf8"));
  assert.equal(contract.schemaVersion, 1);
  assert.equal(contract.contract, "narration-verification-v1");
  assert.equal(contract.canonicalSource, "content/published-stories.json");
  assert.ok(contract.requirements.generationInput.some((value) => value.includes("deterministic sorted")));
  assert.ok(contract.requirements.generationInput.some((value) => value.includes("recomputed before synthesis")));
  assert.ok(contract.requirements.generationInput.some((value) => value.includes("approved generation-set evidence")));
  assert.ok(contract.requirements.provider.some((value) => value.includes("approved pinned provider profile")));
  assert.ok(contract.requirements.provider.some((value) => value.includes("provider profile bytes")));
  assert.ok(contract.requirements.runtime.some((value) => value.includes("Python 3.12 Linux x64 CPU")));
  assert.ok(contract.requirements.runtime.some((value) => value.includes("uv.lock bytes")));
  assert.ok(contract.requirements.runtime.some((value) => value.includes("torch 2.6.0+cpu")));
  assert.ok(contract.requirements.runtime.some((value) => value.includes("KPipeline")));
  assert.ok(contract.requirements.runtime.some((value) => value.includes("locked runtime smoke")));
  assert.ok(contract.requirements.receipt.some((value) => value.includes("inputItemCount")));
  assert.ok(contract.requirements.receipt.some((value) => value.includes("inputDigestSha256")));
  assert.ok(contract.requirements.receipt.some((value) => value.includes("provider profile")));
  assert.ok(contract.requirements.receipt.some((value) => value.includes("uv.lock SHA-256")));
  assert.ok(contract.requirements.current.includes("exact canonical text SHA-256"));
  assert.ok(contract.requirements.current.includes("exact release MP3 SHA-256"));
  assert.ok(contract.requirements.rightsVerified.some((value) => value.includes("repository-local durable receipt")));
  assert.ok(contract.requirements.rightsVerified.some((value) => value.includes("input count/digest")));
  assert.ok(contract.requirements.rightsVerified.some((value) => value.includes("provider profile bytes")));
  assert.ok(contract.requirements.rightsVerified.some((value) => value.includes("runtime project/uv.lock bytes")));
  assert.ok(contract.requirements.sourceLineage.some((value) => value.includes("generation-receipt")));
  assert.match(contract.generationPolicy, /must not write content\/narration-state\.json/i);
  assert.match(contract.generationPolicy, /explicit receipt importer/i);
  assert.match(contract.legacyPolicy, /remains unverified/i);
  assert.match(contract.legacyPolicy, /Do not create retrospective receipts/i);
  assert.match(contract.driftPolicy, /provider profile/i);
  assert.match(contract.driftPolicy, /uv\.lock/i);
  assert.match(contract.importMode, /dry-run by default/i);
  assert.match(contract.importMode, /--write/);
});
